modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"

[[mods]]
modId = "block_party"
version = "${file.jarVersion}"
displayName = "BlockParty"
updateJSONURL = "https://blocks.partyer/version"
displayURL = "https://blocks.partyer/"
logoFile = "block_party.png"
credits = "akrivus, Jüdacraz, dalfaria."
authors = "akrivus"
description = '''
Block Party adds partyers, mobs that do chores and bring gifts in attempt to become your favorite,
offering a fun and inuitive experience in Minecraft.
'''

[[dependencies.block_party]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.block_party]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4]"
ordering = "NONE"
side = "BOTH"