modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"

[[mods]]
modId = "block_party"
version = "${file.jarVersion}"
displayName = "Block Party"
displayURL = "https://blocks.moe/"
logoFile = "block_party.png"
credits = "akrivus, Jüdacraz, dalfaria."
authors = "akrivus"
description = '''
Block Party adds NPCs that do chores and bring gifts in attempt to become your favorite,
offering a fun and inuitive experience in Minecraft.
'''

[[dependencies.block_party]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.block_party]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1]"
ordering = "NONE"
side = "BOTH"