modLoader = "javafml"
loaderVersion = "[0,)"
license = "All Rights Reserved"

[[mods]]
modId = "block_party"
version = "${file.jarVersion}"
displayName = "Block Party"
displayURL = "https://blocks.moe/"
logoFile = "block_party.png"
credits = "akrivus, Jüdacraz, dalfaria."
authors = "akrivus"
description = '''
In Block Party, your blocks to come to life to enjoy the world around them.
'''

[[dependencies.block_party]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.block_party]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"