modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"

[[mods]]
modId = "moeblocks"
version = "${file.jarVersion}"
displayName = "MoeBlocks"
updateJSONURL = "https://blocks.moe/version"
displayURL = "https://blocks.moe/"
logoFile = "moeblocks.png"
credits = "akrivus, Jüdacraz, dalfaria."
authors = "akrivus"
description = '''
MoeBlocks adds moes, mobs that do chores and bring gifts in attempt to become your favorite,
offering a fun and inuitive experience in Minecraft.
'''

[[dependencies.moeblocks]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.moeblocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4]"
ordering = "NONE"
side = "BOTH"