modLoader = "javafml"
loaderVersion = "[33,)"
license = "MIT"

[[mods]]
modId = "moeblocks"
version = "${file.jarVersion}"
displayName = "MoeBlocks"
updateJSONURL = "https://blocks.moe/version"
displayURL = "https://blocks.moe/"
logoFile = "moeblocks.png"
credits = "KAGIC for the idea, Akrivus for the code, Judacraz for textures, Azuraskys for voice lines."
authors = "Akrivus"
description = '''
MoeBlocks adds moes, mobs that do chores and bring gifts in attempt to become your favorite,
offering a fun and inuitive experience in Minecraft.
'''

[[dependencies.moeblocks]]
modId = "forge"
mandatory = true
versionRange = "[33,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.moeblocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2]"
ordering = "NONE"
side = "BOTH"