package moeblocks.init;

import moeblocks.MoeMod;
import moeblocks.item.*;
import moeblocks.util.sort.ISortableItem;
import net.minecraft.block.DispenserBlock;
import net.minecraft.item.Item;
import net.minecraft.item.ItemModelsProperties;
import net.minecraft.item.ItemStack;
import net.minecraft.item.MusicDiscItem;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class MoeItems {
    public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MoeMod.ID);
    public static final RegistryObject<Item> BENTO_BOX = REGISTRY.register("bento_box", BentoBoxItem::new);
    public static final RegistryObject<Item> BLACK_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("black_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLACK_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLACK_BLANK_PAPER_LANTERN = REGISTRY.register("black_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLACK_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> BLACK_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("black_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLACK_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLACK_DAWN_PAPER_LANTERN = REGISTRY.register("black_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLACK_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> BLACK_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("black_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLACK_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLACK_EVENING_PAPER_LANTERN = REGISTRY.register("black_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLACK_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> BLACK_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("black_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLACK_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLACK_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("black_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLACK_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> BLACK_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("black_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLACK_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLACK_MORNING_PAPER_LANTERN = REGISTRY.register("black_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLACK_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> BLACK_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("black_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLACK_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLACK_NIGHT_PAPER_LANTERN = REGISTRY.register("black_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLACK_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> BLACK_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("black_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLACK_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLACK_NOON_PAPER_LANTERN = REGISTRY.register("black_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLACK_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("blue_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLUE_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLUE_BLANK_PAPER_LANTERN = REGISTRY.register("blue_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLUE_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("blue_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLUE_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLUE_DAWN_PAPER_LANTERN = REGISTRY.register("blue_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLUE_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("blue_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLUE_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLUE_EVENING_PAPER_LANTERN = REGISTRY.register("blue_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLUE_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("blue_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLUE_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLUE_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("blue_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLUE_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("blue_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLUE_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLUE_MORNING_PAPER_LANTERN = REGISTRY.register("blue_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLUE_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("blue_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLUE_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLUE_NIGHT_PAPER_LANTERN = REGISTRY.register("blue_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLUE_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("blue_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BLUE_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BLUE_NOON_PAPER_LANTERN = REGISTRY.register("blue_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BLUE_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> BLUE_SPIDER_LILY = REGISTRY.register("blue_spider_lily", () -> new MoeBlockItem(MoeBlocks.BLUE_SPIDER_LILY, 10));
    public static final RegistryObject<Item> BROWN_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("brown_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BROWN_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BROWN_BLANK_PAPER_LANTERN = REGISTRY.register("brown_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BROWN_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> BROWN_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("brown_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BROWN_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BROWN_DAWN_PAPER_LANTERN = REGISTRY.register("brown_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BROWN_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> BROWN_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("brown_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BROWN_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BROWN_EVENING_PAPER_LANTERN = REGISTRY.register("brown_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BROWN_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> BROWN_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("brown_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BROWN_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BROWN_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("brown_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BROWN_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> BROWN_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("brown_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BROWN_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BROWN_MORNING_PAPER_LANTERN = REGISTRY.register("brown_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BROWN_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> BROWN_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("brown_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BROWN_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BROWN_NIGHT_PAPER_LANTERN = REGISTRY.register("brown_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BROWN_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> BROWN_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("brown_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.BROWN_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> BROWN_NOON_PAPER_LANTERN = REGISTRY.register("brown_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.BROWN_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> CALLIGRAPHY_BRUSH = REGISTRY.register("calligraphy_brush", CalligraphyBrushItem::new);
    public static final RegistryObject<Item> CALLIGRAPHY_TABLE = REGISTRY.register("calligraphy_table", () -> new MoeBlockItem(MoeBlocks.CALLIGRAPHY_TABLE, 5));
    public static final RegistryObject<Item> CELL_PHONE = REGISTRY.register("cell_phone", CellPhoneItem::new);
    public static final RegistryObject<Item> CUPCAKE = REGISTRY.register("cupcake", CupcakeItem::new);
    public static final RegistryObject<Item> CYAN_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("cyan_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.CYAN_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> CYAN_BLANK_PAPER_LANTERN = REGISTRY.register("cyan_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.CYAN_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> CYAN_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("cyan_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.CYAN_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> CYAN_DAWN_PAPER_LANTERN = REGISTRY.register("cyan_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.CYAN_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> CYAN_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("cyan_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.CYAN_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> CYAN_EVENING_PAPER_LANTERN = REGISTRY.register("cyan_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.CYAN_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> CYAN_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("cyan_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.CYAN_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> CYAN_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("cyan_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.CYAN_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> CYAN_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("cyan_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.CYAN_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> CYAN_MORNING_PAPER_LANTERN = REGISTRY.register("cyan_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.CYAN_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> CYAN_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("cyan_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.CYAN_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> CYAN_NIGHT_PAPER_LANTERN = REGISTRY.register("cyan_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.CYAN_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> CYAN_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("cyan_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.CYAN_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> CYAN_NOON_PAPER_LANTERN = REGISTRY.register("cyan_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.CYAN_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> GRAY_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("gray_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GRAY_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GRAY_BLANK_PAPER_LANTERN = REGISTRY.register("gray_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GRAY_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> GRAY_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("gray_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GRAY_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GRAY_DAWN_PAPER_LANTERN = REGISTRY.register("gray_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GRAY_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> GRAY_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("gray_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GRAY_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GRAY_EVENING_PAPER_LANTERN = REGISTRY.register("gray_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GRAY_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> GRAY_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("gray_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GRAY_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GRAY_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("gray_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GRAY_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> GRAY_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("gray_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GRAY_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GRAY_MORNING_PAPER_LANTERN = REGISTRY.register("gray_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GRAY_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> GRAY_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("gray_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GRAY_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GRAY_NIGHT_PAPER_LANTERN = REGISTRY.register("gray_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GRAY_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> GRAY_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("gray_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GRAY_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GRAY_NOON_PAPER_LANTERN = REGISTRY.register("gray_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GRAY_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> GREEN_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("green_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GREEN_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GREEN_BLANK_PAPER_LANTERN = REGISTRY.register("green_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GREEN_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> GREEN_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("green_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GREEN_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GREEN_DAWN_PAPER_LANTERN = REGISTRY.register("green_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GREEN_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> GREEN_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("green_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GREEN_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GREEN_EVENING_PAPER_LANTERN = REGISTRY.register("green_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GREEN_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> GREEN_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("green_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GREEN_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GREEN_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("green_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GREEN_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> GREEN_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("green_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GREEN_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GREEN_MORNING_PAPER_LANTERN = REGISTRY.register("green_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GREEN_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> GREEN_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("green_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GREEN_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GREEN_NIGHT_PAPER_LANTERN = REGISTRY.register("green_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GREEN_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> GREEN_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("green_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.GREEN_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> GREEN_NOON_PAPER_LANTERN = REGISTRY.register("green_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.GREEN_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> LETTER = REGISTRY.register("letter", LetterItem::new);
    public static final RegistryObject<Item> LIGHT_BLUE_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("light_blue_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_BLUE_BLANK_PAPER_LANTERN = REGISTRY.register("light_blue_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_BLUE_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("light_blue_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_BLUE_DAWN_PAPER_LANTERN = REGISTRY.register("light_blue_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_BLUE_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("light_blue_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_BLUE_EVENING_PAPER_LANTERN = REGISTRY.register("light_blue_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_BLUE_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("light_blue_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_BLUE_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("light_blue_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_BLUE_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("light_blue_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_BLUE_MORNING_PAPER_LANTERN = REGISTRY.register("light_blue_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_BLUE_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("light_blue_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_BLUE_NIGHT_PAPER_LANTERN = REGISTRY.register("light_blue_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_BLUE_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("light_blue_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_BLUE_NOON_PAPER_LANTERN = REGISTRY.register("light_blue_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_BLUE_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_GRAY_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("light_gray_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_GRAY_BLANK_PAPER_LANTERN = REGISTRY.register("light_gray_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_GRAY_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("light_gray_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_GRAY_DAWN_PAPER_LANTERN = REGISTRY.register("light_gray_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_GRAY_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("light_gray_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_GRAY_EVENING_PAPER_LANTERN = REGISTRY.register("light_gray_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_GRAY_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("light_gray_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_GRAY_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("light_gray_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_GRAY_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("light_gray_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_GRAY_MORNING_PAPER_LANTERN = REGISTRY.register("light_gray_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_GRAY_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("light_gray_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_GRAY_NIGHT_PAPER_LANTERN = REGISTRY.register("light_gray_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> LIGHT_GRAY_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("light_gray_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIGHT_GRAY_NOON_PAPER_LANTERN = REGISTRY.register("light_gray_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIGHT_GRAY_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> LIME_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("lime_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIME_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIME_BLANK_PAPER_LANTERN = REGISTRY.register("lime_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIME_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> LIME_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("lime_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIME_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIME_DAWN_PAPER_LANTERN = REGISTRY.register("lime_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIME_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> LIME_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("lime_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIME_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIME_EVENING_PAPER_LANTERN = REGISTRY.register("lime_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIME_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> LIME_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("lime_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIME_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIME_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("lime_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIME_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> LIME_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("lime_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIME_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIME_MORNING_PAPER_LANTERN = REGISTRY.register("lime_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIME_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> LIME_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("lime_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIME_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIME_NIGHT_PAPER_LANTERN = REGISTRY.register("lime_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIME_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> LIME_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("lime_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.LIME_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> LIME_NOON_PAPER_LANTERN = REGISTRY.register("lime_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.LIME_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> MAGENTA_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("magenta_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.MAGENTA_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> MAGENTA_BLANK_PAPER_LANTERN = REGISTRY.register("magenta_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.MAGENTA_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> MAGENTA_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("magenta_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.MAGENTA_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> MAGENTA_DAWN_PAPER_LANTERN = REGISTRY.register("magenta_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.MAGENTA_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> MAGENTA_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("magenta_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.MAGENTA_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> MAGENTA_EVENING_PAPER_LANTERN = REGISTRY.register("magenta_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.MAGENTA_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> MAGENTA_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("magenta_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.MAGENTA_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> MAGENTA_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("magenta_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.MAGENTA_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> MAGENTA_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("magenta_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.MAGENTA_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> MAGENTA_MORNING_PAPER_LANTERN = REGISTRY.register("magenta_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.MAGENTA_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> MAGENTA_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("magenta_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.MAGENTA_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> MAGENTA_NIGHT_PAPER_LANTERN = REGISTRY.register("magenta_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.MAGENTA_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> MAGENTA_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("magenta_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.MAGENTA_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> MAGENTA_NOON_PAPER_LANTERN = REGISTRY.register("magenta_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.MAGENTA_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> MOE_DIE = REGISTRY.register("moe_die", MoeDieItem::new);
    public static final RegistryObject<Item> MOE_SPAWN_EGG = REGISTRY.register("moe_spawn_egg", MoeSpawnItem::new);
    public static final RegistryObject<Item> ONIGIRI = REGISTRY.register("onigiri", OnigiriItem::new);
    public static final RegistryObject<Item> ORANGE_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("orange_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.ORANGE_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> ORANGE_BLANK_PAPER_LANTERN = REGISTRY.register("orange_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.ORANGE_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> ORANGE_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("orange_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.ORANGE_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> ORANGE_DAWN_PAPER_LANTERN = REGISTRY.register("orange_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.ORANGE_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> ORANGE_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("orange_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.ORANGE_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> ORANGE_EVENING_PAPER_LANTERN = REGISTRY.register("orange_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.ORANGE_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> ORANGE_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("orange_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.ORANGE_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> ORANGE_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("orange_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.ORANGE_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> ORANGE_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("orange_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.ORANGE_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> ORANGE_MORNING_PAPER_LANTERN = REGISTRY.register("orange_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.ORANGE_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> ORANGE_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("orange_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.ORANGE_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> ORANGE_NIGHT_PAPER_LANTERN = REGISTRY.register("orange_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.ORANGE_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> ORANGE_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("orange_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.ORANGE_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> ORANGE_NOON_PAPER_LANTERN = REGISTRY.register("orange_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.ORANGE_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("pink_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PINK_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PINK_BLANK_PAPER_LANTERN = REGISTRY.register("pink_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PINK_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_BOW = REGISTRY.register("pink_bow", PinkBowItem::new);
    public static final RegistryObject<Item> PINK_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("pink_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PINK_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PINK_DAWN_PAPER_LANTERN = REGISTRY.register("pink_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PINK_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("pink_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PINK_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PINK_EVENING_PAPER_LANTERN = REGISTRY.register("pink_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PINK_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("pink_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PINK_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PINK_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("pink_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PINK_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("pink_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PINK_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PINK_MORNING_PAPER_LANTERN = REGISTRY.register("pink_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PINK_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("pink_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PINK_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PINK_NIGHT_PAPER_LANTERN = REGISTRY.register("pink_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PINK_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("pink_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PINK_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PINK_NOON_PAPER_LANTERN = REGISTRY.register("pink_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PINK_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> PINK_SAKURA_BLOSSOMS = REGISTRY.register("pink_sakura_blossoms", () -> new MoeBlockItem(MoeBlocks.PINK_SAKURA_BLOSSOMS, 10));
    public static final RegistryObject<Item> PINK_SAKURA_SAPLING = REGISTRY.register("pink_sakura_sapling", () -> new MoeBlockItem(MoeBlocks.PINK_SAKURA_SAPLING, 10));
    public static final RegistryObject<Item> PURPLE_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("purple_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PURPLE_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PURPLE_BLANK_PAPER_LANTERN = REGISTRY.register("purple_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PURPLE_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> PURPLE_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("purple_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PURPLE_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PURPLE_DAWN_PAPER_LANTERN = REGISTRY.register("purple_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PURPLE_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> PURPLE_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("purple_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PURPLE_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PURPLE_EVENING_PAPER_LANTERN = REGISTRY.register("purple_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PURPLE_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> PURPLE_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("purple_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PURPLE_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PURPLE_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("purple_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PURPLE_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> PURPLE_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("purple_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PURPLE_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PURPLE_MORNING_PAPER_LANTERN = REGISTRY.register("purple_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PURPLE_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> PURPLE_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("purple_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PURPLE_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PURPLE_NIGHT_PAPER_LANTERN = REGISTRY.register("purple_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PURPLE_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> PURPLE_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("purple_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.PURPLE_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> PURPLE_NOON_PAPER_LANTERN = REGISTRY.register("purple_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.PURPLE_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("red_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.RED_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> RED_BLANK_PAPER_LANTERN = REGISTRY.register("red_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.RED_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("red_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.RED_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> RED_DAWN_PAPER_LANTERN = REGISTRY.register("red_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.RED_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("red_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.RED_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> RED_EVENING_PAPER_LANTERN = REGISTRY.register("red_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.RED_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("red_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.RED_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> RED_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("red_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.RED_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("red_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.RED_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> RED_MORNING_PAPER_LANTERN = REGISTRY.register("red_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.RED_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("red_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.RED_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> RED_NIGHT_PAPER_LANTERN = REGISTRY.register("red_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.RED_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("red_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.RED_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> RED_NOON_PAPER_LANTERN = REGISTRY.register("red_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.RED_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> RED_SPIDER_LILY = REGISTRY.register("red_spider_lily", () -> new MoeBlockItem(MoeBlocks.RED_SPIDER_LILY, 10));
    public static final RegistryObject<Item> SAKURA_BUTTON = REGISTRY.register("sakura_button", () -> new MoeBlockItem(MoeBlocks.SAKURA_BUTTON, 20));
    public static final RegistryObject<Item> SAKURA_FENCE = REGISTRY.register("sakura_fence", () -> new MoeBlockItem(MoeBlocks.SAKURA_FENCE, 20));
    public static final RegistryObject<Item> SAKURA_FENCE_GATE = REGISTRY.register("sakura_fence_gate", () -> new MoeBlockItem(MoeBlocks.SAKURA_FENCE_GATE, 20));
    public static final RegistryObject<Item> SAKURA_LOG = REGISTRY.register("sakura_log", () -> new MoeBlockItem(MoeBlocks.SAKURA_LOG, 20));
    public static final RegistryObject<Item> SAKURA_PLANKS = REGISTRY.register("sakura_planks", () -> new MoeBlockItem(MoeBlocks.SAKURA_PLANKS, 20));
    public static final RegistryObject<Item> SAKURA_PRESSURE_PLATE = REGISTRY.register("sakura_pressure_plate", () -> new MoeBlockItem(MoeBlocks.SAKURA_PRESSURE_PLATE, 20));
    public static final RegistryObject<Item> SAKURA_SLAB = REGISTRY.register("sakura_slab", () -> new MoeBlockItem(MoeBlocks.SAKURA_SLAB, 20));
    public static final RegistryObject<Item> SAKURA_STAIRS = REGISTRY.register("sakura_stairs", () -> new MoeBlockItem(MoeBlocks.SAKURA_STAIRS, 20));
    public static final RegistryObject<Item> SAKURA_WOOD = REGISTRY.register("sakura_wood", () -> new MoeBlockItem(MoeBlocks.SAKURA_WOOD, 20));
    public static final RegistryObject<Item> SHOJI_BLOCK = REGISTRY.register("shoji_block", () -> new MoeBlockItem(MoeBlocks.SHOJI_BLOCK, 20));
    public static final RegistryObject<Item> SHOJI_LANTERN = REGISTRY.register("shoji_lantern", () -> new MoeBlockItem(MoeBlocks.SHOJI_LANTERN, 20));
    public static final RegistryObject<Item> SHOJI_PANEL = REGISTRY.register("shoji_panel", () -> new MoeBlockItem(MoeBlocks.SHOJI_PANEL, 20));
    public static final RegistryObject<Item> SHOJI_SCREEN = REGISTRY.register("shoji_screen", () -> new MoeBlockItem(MoeBlocks.SHOJI_SCREEN, 20));
    public static final RegistryObject<Item> STRIPPED_SAKURA_LOG = REGISTRY.register("stripped_sakura_log", () -> new MoeBlockItem(MoeBlocks.STRIPPED_SAKURA_LOG, 20));
    public static final RegistryObject<Item> STRIPPED_SAKURA_WOOD = REGISTRY.register("stripped_sakura_wood", () -> new MoeBlockItem(MoeBlocks.STRIPPED_SAKURA_WOOD, 20));
    public static final RegistryObject<Item> TATAMI_MAT = REGISTRY.register("tatami_mat", () -> new MoeBlockItem(MoeBlocks.TATAMI_MAT, 20));
    public static final RegistryObject<Item> WHITE_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("white_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.WHITE_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> WHITE_BLANK_PAPER_LANTERN = REGISTRY.register("white_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.WHITE_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> WHITE_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("white_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.WHITE_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> WHITE_DAWN_PAPER_LANTERN = REGISTRY.register("white_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.WHITE_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> WHITE_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("white_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.WHITE_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> WHITE_EVENING_PAPER_LANTERN = REGISTRY.register("white_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.WHITE_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> WHITE_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("white_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.WHITE_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> WHITE_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("white_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.WHITE_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> WHITE_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("white_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.WHITE_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> WHITE_MORNING_PAPER_LANTERN = REGISTRY.register("white_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.WHITE_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> WHITE_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("white_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.WHITE_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> WHITE_NIGHT_PAPER_LANTERN = REGISTRY.register("white_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.WHITE_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> WHITE_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("white_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.WHITE_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> WHITE_NOON_PAPER_LANTERN = REGISTRY.register("white_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.WHITE_NOON_PAPER_LANTERN));
    public static final RegistryObject<Item> WHITE_SAKURA_BLOSSOMS = REGISTRY.register("white_sakura_blossoms", () -> new MoeBlockItem(MoeBlocks.WHITE_SAKURA_BLOSSOMS, 10));
    public static final RegistryObject<Item> WHITE_SAKURA_SAPLING = REGISTRY.register("white_sakura_sapling", () -> new MoeBlockItem(MoeBlocks.WHITE_SAKURA_SAPLING, 10));
    public static final RegistryObject<Item> WISTERIA_BINE = REGISTRY.register("wisteria_bine", () -> new MoeBlockItem(MoeBlocks.WISTERIA_BINE, 20));
    public static final RegistryObject<Item> WISTERIA_LEAVES = REGISTRY.register("wisteria_leaves", () -> new MoeBlockItem(MoeBlocks.WISTERIA_LEAVES, 20));
    public static final RegistryObject<Item> WISTERIA_SAPLING = REGISTRY.register("wisteria_sapling", () -> new MoeBlockItem(MoeBlocks.WISTERIA_SAPLING, 20));
    public static final RegistryObject<Item> WISTERIA_VINES = REGISTRY.register("wisteria_vines", () -> new MoeBlockItem(MoeBlocks.WISTERIA_VINE_TIP, 20));
    public static final RegistryObject<Item> YEARBOOK = REGISTRY.register("yearbook", YearbookItem::new);
    public static final RegistryObject<Item> YEARBOOK_PAGE = REGISTRY.register("yearbook_page", YearbookPageItem::new);
    public static final RegistryObject<Item> YELLOW_BLANK_CALLIGRAPHY_SCROLL = REGISTRY.register("yellow_blank_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.YELLOW_BLANK_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> YELLOW_BLANK_PAPER_LANTERN = REGISTRY.register("yellow_blank_paper_lantern", () -> new MoeBlockItem(MoeBlocks.YELLOW_BLANK_PAPER_LANTERN));
    public static final RegistryObject<Item> YELLOW_DAWN_CALLIGRAPHY_SCROLL = REGISTRY.register("yellow_dawn_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.YELLOW_DAWN_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> YELLOW_DAWN_PAPER_LANTERN = REGISTRY.register("yellow_dawn_paper_lantern", () -> new MoeBlockItem(MoeBlocks.YELLOW_DAWN_PAPER_LANTERN));
    public static final RegistryObject<Item> YELLOW_EVENING_CALLIGRAPHY_SCROLL = REGISTRY.register("yellow_evening_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.YELLOW_EVENING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> YELLOW_EVENING_PAPER_LANTERN = REGISTRY.register("yellow_evening_paper_lantern", () -> new MoeBlockItem(MoeBlocks.YELLOW_EVENING_PAPER_LANTERN));
    public static final RegistryObject<Item> YELLOW_MIDNIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("yellow_midnight_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.YELLOW_MIDNIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> YELLOW_MIDNIGHT_PAPER_LANTERN = REGISTRY.register("yellow_midnight_paper_lantern", () -> new MoeBlockItem(MoeBlocks.YELLOW_MIDNIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> YELLOW_MORNING_CALLIGRAPHY_SCROLL = REGISTRY.register("yellow_morning_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.YELLOW_MORNING_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> YELLOW_MORNING_PAPER_LANTERN = REGISTRY.register("yellow_morning_paper_lantern", () -> new MoeBlockItem(MoeBlocks.YELLOW_MORNING_PAPER_LANTERN));
    public static final RegistryObject<Item> YELLOW_NIGHT_CALLIGRAPHY_SCROLL = REGISTRY.register("yellow_night_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.YELLOW_NIGHT_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> YELLOW_NIGHT_PAPER_LANTERN = REGISTRY.register("yellow_night_paper_lantern", () -> new MoeBlockItem(MoeBlocks.YELLOW_NIGHT_PAPER_LANTERN));
    public static final RegistryObject<Item> YELLOW_NOON_CALLIGRAPHY_SCROLL = REGISTRY.register("yellow_noon_calligraphy_scroll", () -> new MoeBlockItem(MoeBlocks.YELLOW_NOON_CALLIGRAPHY_SCROLL));
    public static final RegistryObject<Item> YELLOW_NOON_PAPER_LANTERN = REGISTRY.register("yellow_noon_paper_lantern", () -> new MoeBlockItem(MoeBlocks.YELLOW_NOON_PAPER_LANTERN));

    public static void registerDispenserBehaviors() {
        DispenserBlock.registerDispenseBehavior(MoeItems.MOE_DIE.get(), MoeDieItem.DISPENSER_BEHAVIOR);
    }
    
    public static void registerModelProperties() {
        ItemModelsProperties.registerProperty(MoeItems.LETTER.get(), LetterItem.CLOSED_PROPERTY, LetterItem.CLOSED_PROPERTY_GETTER);
    }

    public static int compare(ItemStack one, ItemStack two) {
        Item item1 = one.getItem();
        Item item2 = two.getItem();
        String name1 = item1.getRegistryName().getPath();
        String name2 = item2.getRegistryName().getPath();
        if (item1 instanceof ISortableItem && item2 instanceof ISortableItem) {
            int sort1 = ((ISortableItem) item1).getSortOrder();
            int sort2 = ((ISortableItem) item2).getSortOrder();
            int sorts = Integer.compare(sort1, sort2);
            if (sorts == 0) {
                return name1.compareToIgnoreCase(name2);
            } else {
                return sorts;
            }
        } else if (item1 instanceof ISortableItem) {
            return  1;
        } else if (item2 instanceof ISortableItem) {
            return -1;
        } else {
            return name1.compareToIgnoreCase(name2);
        }
    }
}
