package moeblocks.init;

import moeblocks.MoeMod;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class MoeSounds {
    public static final DeferredRegister<SoundEvent> REGISTRY = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, MoeMod.ID);

    public static final RegistryObject<SoundEvent> CELL_PHONE_BUTTON = REGISTRY.register("item.cell_phone.button", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "item.cell_phone.button")));
    public static final RegistryObject<SoundEvent> CELL_PHONE_DIAL = REGISTRY.register("item.cell_phone.dial", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "item.cell_phone.dial")));
    public static final RegistryObject<SoundEvent> CELL_PHONE_RING = REGISTRY.register("item.cell_phone.ring", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "item.cell_phone.ring")));
    public static final RegistryObject<SoundEvent> MOE_BELL_STEP = REGISTRY.register("entity.moe.bell.step", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.bell.step")));
    public static final RegistryObject<SoundEvent> MOE_BOY_ANGRY = REGISTRY.register("entity.moe.boy.angry", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.angry")));
    public static final RegistryObject<SoundEvent> MOE_BOY_ATTACK = REGISTRY.register("entity.moe.boy.attack", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.attack")));
    public static final RegistryObject<SoundEvent> MOE_BOY_CONFUSED = REGISTRY.register("entity.moe.boy.confused", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.confused")));
    public static final RegistryObject<SoundEvent> MOE_BOY_CRYING = REGISTRY.register("entity.moe.boy.crying", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.crying")));
    public static final RegistryObject<SoundEvent> MOE_BOY_DEAD = REGISTRY.register("entity.moe.boy.dead", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.dead")));
    public static final RegistryObject<SoundEvent> MOE_BOY_EAT = REGISTRY.register("entity.moe.boy.eat", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.eat")));
    public static final RegistryObject<SoundEvent> MOE_BOY_EQUIP = REGISTRY.register("entity.moe.boy.equip", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.equip")));
    public static final RegistryObject<SoundEvent> MOE_BOY_FEED = REGISTRY.register("entity.moe.boy.feed", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.feed")));
    public static final RegistryObject<SoundEvent> MOE_BOY_FOLLOW = REGISTRY.register("entity.moe.boy.follow", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.follow")));
    public static final RegistryObject<SoundEvent> MOE_BOY_GIGGLE = REGISTRY.register("entity.moe.boy.giggle", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.giggle")));
    public static final RegistryObject<SoundEvent> MOE_BOY_GRIEF = REGISTRY.register("entity.moe.boy.grief", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.grief")));
    public static final RegistryObject<SoundEvent> MOE_BOY_HAPPY = REGISTRY.register("entity.moe.boy.happy", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.happy")));
    public static final RegistryObject<SoundEvent> MOE_BOY_HELLO = REGISTRY.register("entity.moe.boy.hello", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.hello")));
    public static final RegistryObject<SoundEvent> MOE_BOY_HURT = REGISTRY.register("entity.moe.boy.hurt", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.hurt")));
    public static final RegistryObject<SoundEvent> MOE_BOY_LAUGH = REGISTRY.register("entity.moe.boy.laugh", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.laugh")));
    public static final RegistryObject<SoundEvent> MOE_BOY_MEOW = REGISTRY.register("entity.moe.boy.meow", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.meow")));
    public static final RegistryObject<SoundEvent> MOE_BOY_NEUTRAL = REGISTRY.register("entity.moe.boy.neutral", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.neutral")));
    public static final RegistryObject<SoundEvent> MOE_BOY_NO = REGISTRY.register("entity.moe.boy.no", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.no")));
    public static final RegistryObject<SoundEvent> MOE_BOY_PSYCHOTIC = REGISTRY.register("entity.moe.boy.psychotic", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.psychotic")));
    public static final RegistryObject<SoundEvent> MOE_BOY_SENPAI = REGISTRY.register("entity.moe.boy.senpai", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.senpai")));
    public static final RegistryObject<SoundEvent> MOE_BOY_SLEEPING = REGISTRY.register("entity.moe.boy.sleeping", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.sleeping")));
    public static final RegistryObject<SoundEvent> MOE_BOY_SMITTEN = REGISTRY.register("entity.moe.boy.smitten", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.smitten")));
    public static final RegistryObject<SoundEvent> MOE_BOY_SNEEZE = REGISTRY.register("entity.moe.boy.sneeze", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.sneeze")));
    public static final RegistryObject<SoundEvent> MOE_BOY_SNICKER = REGISTRY.register("entity.moe.boy.snicker", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.snicker")));
    public static final RegistryObject<SoundEvent> MOE_BOY_SNOOTY = REGISTRY.register("entity.moe.boy.snooty", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.snooty")));
    public static final RegistryObject<SoundEvent> MOE_BOY_YAWN = REGISTRY.register("entity.moe.boy.yawn", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.yawn")));
    public static final RegistryObject<SoundEvent> MOE_BOY_YES = REGISTRY.register("entity.moe.boy.yes", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.boy.yes")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_ANGRY = REGISTRY.register("entity.moe.girl.angry", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.angry")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_ATTACK = REGISTRY.register("entity.moe.girl.attack", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.attack")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_CONFUSED = REGISTRY.register("entity.moe.girl.confused", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.confused")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_CRYING = REGISTRY.register("entity.moe.girl.crying", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.crying")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_DEAD = REGISTRY.register("entity.moe.girl.dead", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.dead")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_EAT = REGISTRY.register("entity.moe.girl.eat", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.eat")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_EQUIP = REGISTRY.register("entity.moe.girl.equip", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.equip")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_FEED = REGISTRY.register("entity.moe.girl.feed", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.feed")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_FOLLOW = REGISTRY.register("entity.moe.girl.follow", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.follow")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_GIGGLE = REGISTRY.register("entity.moe.girl.giggle", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.giggle")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_GRIEF = REGISTRY.register("entity.moe.girl.grief", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.grief")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_HAPPY = REGISTRY.register("entity.moe.girl.happy", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.happy")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_HELLO = REGISTRY.register("entity.moe.girl.hello", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.hello")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_HURT = REGISTRY.register("entity.moe.girl.hurt", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.hurt")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_LAUGH = REGISTRY.register("entity.moe.girl.laugh", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.laugh")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_MEOW = REGISTRY.register("entity.moe.girl.meow", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.meow")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_NEUTRAL = REGISTRY.register("entity.moe.girl.neutral", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.neutral")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_NO = REGISTRY.register("entity.moe.girl.no", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.no")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_PSYCHOTIC = REGISTRY.register("entity.moe.girl.psychotic", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.psychotic")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_SENPAI = REGISTRY.register("entity.moe.girl.senpai", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.senpai")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_SLEEPING = REGISTRY.register("entity.moe.girl.sleeping", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.sleeping")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_SMITTEN = REGISTRY.register("entity.moe.girl.smitten", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.smitten")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_SNEEZE = REGISTRY.register("entity.moe.girl.sneeze", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.sneeze")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_SNICKER = REGISTRY.register("entity.moe.girl.snicker", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.snicker")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_SNOOTY = REGISTRY.register("entity.moe.girl.snooty", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.snooty")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_YAWN = REGISTRY.register("entity.moe.girl.yawn", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.yawn")));
    public static final RegistryObject<SoundEvent> MOE_GIRL_YES = REGISTRY.register("entity.moe.girl.yes", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.girl.yes")));
    public static final RegistryObject<SoundEvent> SENPAI_ANGRY = REGISTRY.register("entity.senpai.angry", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.angry")));
    public static final RegistryObject<SoundEvent> SENPAI_ATTACK = REGISTRY.register("entity.senpai.attack", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.attack")));
    public static final RegistryObject<SoundEvent> SENPAI_CONFUSED = REGISTRY.register("entity.senpai.confused", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.confused")));
    public static final RegistryObject<SoundEvent> SENPAI_CRYING = REGISTRY.register("entity.senpai.crying", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.crying")));
    public static final RegistryObject<SoundEvent> SENPAI_DEAD = REGISTRY.register("entity.senpai.dead", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.dead")));
    public static final RegistryObject<SoundEvent> SENPAI_EAT = REGISTRY.register("entity.senpai.eat", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.eat")));
    public static final RegistryObject<SoundEvent> SENPAI_EQUIP = REGISTRY.register("entity.senpai.equip", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.equip")));
    public static final RegistryObject<SoundEvent> SENPAI_FEED = REGISTRY.register("entity.senpai.feed", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.feed")));
    public static final RegistryObject<SoundEvent> SENPAI_FOLLOW = REGISTRY.register("entity.senpai.follow", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.follow")));
    public static final RegistryObject<SoundEvent> SENPAI_GIGGLE = REGISTRY.register("entity.senpai.giggle", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.giggle")));
    public static final RegistryObject<SoundEvent> SENPAI_GRIEF = REGISTRY.register("entity.senpai.grief", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.grief")));
    public static final RegistryObject<SoundEvent> SENPAI_HAPPY = REGISTRY.register("entity.senpai.happy", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.happy")));
    public static final RegistryObject<SoundEvent> SENPAI_HELLO = REGISTRY.register("entity.senpai.hello", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.hello")));
    public static final RegistryObject<SoundEvent> SENPAI_HURT = REGISTRY.register("entity.senpai.hurt", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.hurt")));
    public static final RegistryObject<SoundEvent> SENPAI_LAUGH = REGISTRY.register("entity.senpai.laugh", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.laugh")));
    public static final RegistryObject<SoundEvent> SENPAI_MEOW = REGISTRY.register("entity.senpai.meow", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.meow")));
    public static final RegistryObject<SoundEvent> SENPAI_NEUTRAL = REGISTRY.register("entity.senpai.neutral", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.neutral")));
    public static final RegistryObject<SoundEvent> SENPAI_NO = REGISTRY.register("entity.senpai.no", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.no")));
    public static final RegistryObject<SoundEvent> SENPAI_PSYCHOTIC = REGISTRY.register("entity.senpai.psychotic", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.psychotic")));
    public static final RegistryObject<SoundEvent> SENPAI_SENPAI = REGISTRY.register("entity.senpai.senpai", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.senpai")));
    public static final RegistryObject<SoundEvent> SENPAI_SLEEPING = REGISTRY.register("entity.senpai.sleeping", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.sleeping")));
    public static final RegistryObject<SoundEvent> SENPAI_SMITTEN = REGISTRY.register("entity.senpai.smitten", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.smitten")));
    public static final RegistryObject<SoundEvent> SENPAI_SNEEZE = REGISTRY.register("entity.senpai.sneeze", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.sneeze")));
    public static final RegistryObject<SoundEvent> SENPAI_SNICKER = REGISTRY.register("entity.senpai.snicker", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.snicker")));
    public static final RegistryObject<SoundEvent> SENPAI_SNOOTY = REGISTRY.register("entity.senpai.snooty", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.snooty")));
    public static final RegistryObject<SoundEvent> SENPAI_YAWN = REGISTRY.register("entity.senpai.yawn", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.yawn")));
    public static final RegistryObject<SoundEvent> SENPAI_YES = REGISTRY.register("entity.senpai.yes", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.yes")));
    public static final RegistryObject<SoundEvent> YEARBOOK_REMOVE_PAGE = REGISTRY.register("item.yearbook.remove_page", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "item.yearbook.remove_page")));
}
