const state={project:null,path:'',selected:null,diagnostics:[],undo:[],redo:[],dirty:false,filter:'ALL',search:''};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));

async function api(path,body){const options=body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};const response=await fetch('/api/'+path,options);const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed');return result}
async function load(){try{const data=await api('project');state.project=data.project;state.path=data.path;normalize();$('#project-path').textContent=data.path;render();await validate()}catch(e){toast(e.message,true)}}
function normalize(){for(const [i,n] of state.project.nodes.entries()){n.conditions??=[];n.actions??=[];n.responses??=[];n.editor??={x:80+(i%3)*290,y:80+Math.floor(i/3)*190}}}
function snapshot(){state.undo.push(JSON.stringify(state.project));if(state.undo.length>80)state.undo.shift();state.redo=[]}
function changed(renderAll=true){state.dirty=true;$('#dirty').textContent='Unsaved';$('#save').disabled=false;if(renderAll)render();scheduleValidate()}
function restore(stack,to){if(!stack.length)return;to.push(JSON.stringify(state.project));state.project=JSON.parse(stack.pop());normalize();if(!state.project.nodes.some(n=>n.id===state.selected))state.selected=null;changed()}

function render(){renderHeader();renderOutline();renderCanvas();renderInspector();$('#undo').disabled=!state.undo.length;$('#redo').disabled=!state.redo.length}
function renderHeader(){const p=state.project;$('#pack-title').textContent=p.pack?.title||p.pack?.id||'Conversation';$('#pack-meta').textContent=`${p.nodes.length} cards · ${p.target?.minecraft||'Minecraft'}`;$('#card-count').textContent=p.nodes.length}
function visible(n){const q=state.search.toLowerCase();return(state.filter==='ALL'||n.type===state.filter)&&(!q||[n.id,n.title,n.text,n.trigger,n.ending].join(' ').toLowerCase().includes(q))}
function renderOutline(){const root=$('#outline');root.innerHTML='';for(const n of state.project.nodes.filter(visible)){const b=document.createElement('button');b.className='outline-item'+(n.id===state.selected?' active':'');b.innerHTML=`<i class="mini-type ${n.type}"></i><span>${esc(n.title||n.id)}</span>`;b.onclick=()=>select(n.id,true);root.append(b)}}
function renderCanvas(){const cards=$('#cards');cards.innerHTML='';const shown=new Set(state.project.nodes.filter(visible).map(n=>n.id));for(const n of state.project.nodes.filter(visible)){const card=document.createElement('article');card.className=`node-card ${n.type}${n.id===state.selected?' selected':''}${state.diagnostics.some(d=>d.node===n.id&&d.severity==='ERROR')?' has-error':''}`;card.style.left=n.editor.x+'px';card.style.top=n.editor.y+'px';card.dataset.id=n.id;const targetCount=targets(n).length;card.innerHTML=`<div class="card-top"><i class="card-type"></i><span class="card-title">${esc(n.title||n.id)}</span><span class="card-id">${esc(n.id)}</span></div><div class="card-text">${esc((n.text||n.ending||'No dialogue').slice(0,130))}</div><div class="card-footer"><span>${n.conditions.length} conditions · ${n.actions.length} actions</span><span class="port">${targetCount} →</span></div>`;card.onpointerdown=e=>dragStart(e,n,card);card.onclick=()=>select(n.id);cards.append(card)}drawEdges(shown)}
function targets(n){return[...(n.responses||[]).map(r=>({id:r.target,label:r.label,type:r.transition})),...(n.next?[{id:n.next,label:'next',type:'EXTERNAL_EVENT'}]:[])]}
function drawEdges(shown){const svg=$('#edges');svg.innerHTML='';for(const n of state.project.nodes){if(!shown.has(n.id))continue;for(const target of targets(n)){const dest=state.project.nodes.find(x=>x.id===target.id);if(!dest||!shown.has(dest.id))continue;const x1=n.editor.x+230,y1=n.editor.y+60,x2=dest.editor.x,y2=dest.editor.y+60,mid=(x1+x2)/2;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${x1} ${y1} C ${mid} ${y1}, ${mid} ${y2}, ${x2} ${y2}`);path.setAttribute('class','edge '+(target.type==='IMMEDIATE'?'':'later'));svg.append(path)}}}
function dragStart(e,node,card){if(e.button!==0)return;select(node.id);const start={x:e.clientX,y:e.clientY,nx:node.editor.x,ny:node.editor.y};let moved=false;card.setPointerCapture(e.pointerId);card.onpointermove=ev=>{if(Math.abs(ev.clientX-start.x)+Math.abs(ev.clientY-start.y)>4)moved=true;if(!moved)return;node.editor.x=Math.max(0,start.nx+ev.clientX-start.x);node.editor.y=Math.max(0,start.ny+ev.clientY-start.y);card.style.left=node.editor.x+'px';card.style.top=node.editor.y+'px';drawEdges(new Set(state.project.nodes.filter(visible).map(n=>n.id)))};card.onpointerup=()=>{card.onpointermove=null;if(moved){state.undo.push(JSON.stringify({...state.project,nodes:state.project.nodes.map(n=>n.id===node.id?{...n,editor:{x:start.nx,y:start.ny}}:n)}));state.redo=[];changed(false)}}}
function select(id,scroll=false){state.selected=id;render();if(scroll){const n=state.project.nodes.find(x=>x.id===id);$('#viewport').scrollTo({left:Math.max(0,n.editor.x-100),top:Math.max(0,n.editor.y-80),behavior:'smooth'})}}

function renderInspector(){const n=selected();$('#empty-inspector').hidden=!!n;$('#card-form').hidden=!n;if(!n)return;const f=$('#card-form');for(const key of ['id','title','type','trigger','text','next','ending'])f.elements[key].value=n[key]??'';$('#type-badge').textContent=n.type;$('#response-count').textContent=n.responses.length;$('#condition-count').textContent=n.conditions.length;$('#action-count').textContent=n.actions.length;$('#conditions-json').value=JSON.stringify(n.conditions,null,2);$('#actions-json').value=JSON.stringify(n.actions,null,2);$('#node-ids').innerHTML=state.project.nodes.filter(x=>x.id!==n.id).map(x=>`<option value="${esc(x.id)}">`).join('');renderResponses(n)}
function selected(){return state.project.nodes.find(n=>n.id===state.selected)}
function editSelected(fn){const n=selected();if(!n)return;snapshot();fn(n);changed()}
function renderResponses(n){const root=$('#responses');root.innerHTML='';n.responses.forEach((r,i)=>{const box=document.createElement('div');box.className='response';box.innerHTML=`<button type="button" class="response-remove" aria-label="Remove response">×</button><div class="response-grid"><label>Label<input data-key="label" value="${attr(r.label||'')}"></label><label>Cue<input data-key="cue" value="${attr(r.cue||'')}"></label><label>Target<input data-key="target" list="node-ids" value="${attr(r.target||'')}"></label><label>Transition<select data-key="transition">${['IMMEDIATE','LATER_INTERACTION','EXTERNAL_EVENT','PACK_EXIT'].map(v=>`<option${r.transition===v?' selected':''}>${v}</option>`).join('')}</select></label></div>`;box.querySelector('.response-remove').onclick=()=>editSelected(x=>x.responses.splice(i,1));box.querySelectorAll('[data-key]').forEach(input=>input.onchange=()=>editSelected(x=>x.responses[i][input.dataset.key]=input.value));root.append(box)})}

let validationTimer;function scheduleValidate(){clearTimeout(validationTimer);validationTimer=setTimeout(validate,280)}
async function validate(){try{const report=await api('validate',{project:state.project});state.diagnostics=report.diagnostics||[];renderDiagnostics();renderCanvas()}catch(e){toast(e.message,true)}}
function renderDiagnostics(){const root=$('#diagnostics');root.innerHTML='';$('#check-count').textContent=state.diagnostics.length||'✓';if(!state.diagnostics.length){root.innerHTML='<div class="all-clear">Everything connects cleanly.</div>';return}for(const d of state.diagnostics){const item=document.createElement('div');item.className='diagnostic '+d.severity;item.innerHTML=`<b>${esc(d.severity)} · ${esc(d.code)}</b>${esc(d.message)}`;if(d.node)item.onclick=()=>select(d.node,true);root.append(item)}}

async function save(){if(state.diagnostics.some(d=>d.severity==='ERROR'))return toast('Resolve validation errors before saving.',true);try{await api('save',{project:state.project});state.dirty=false;$('#dirty').textContent='Saved';$('#save').disabled=true;toast('Project saved')}catch(e){toast(e.message,true)}}
async function runSimulation(){try{const scenario={cookies:json($('#scenario-cookies').value),counters:json($('#scenario-counters').value),inventory:json($('#scenario-inventory').value)};const r=await api('simulate',{project:state.project,scenario});$('#simulation-results').innerHTML=`<div class="stat-grid"><div class="stat"><b>${r.routes}</b><span>Routes</span></div><div class="stat"><b>${r.endings.length}</b><span>Endings</span></div><div class="stat"><b>${r.cycles.length}</b><span>Cycles</span></div></div><h3>Traces</h3>${r.traces.map(t=>`<div class="route">${t.map(esc).join(' → ')}</div>`).join('')||'<p>No routes found.</p>'}<p><b>External requirements:</b> ${r.externalRequirements.map(esc).join(', ')||'none'}</p>`}catch(e){$('#simulation-results').innerHTML=`<p class="diagnostic ERROR">${esc(e.message)}</p>`}}
async function runExport(){try{const r=await api('export',{project:state.project,output:$('#export-path').value});$('#export-result').innerHTML=`<p class="all-clear">Exported ${r.datapackFiles} datapack files across ${r.routes} routes to<br><b>${esc(r.output)}</b></p>`}catch(e){$('#export-result').innerHTML=`<p class="diagnostic ERROR">${esc(e.message)}</p>`}}

$('#card-form').addEventListener('change',e=>{if(!e.target.name)return;const key=e.target.name;editSelected(n=>{if(key==='id'){const old=n.id;n.id=e.target.value;if(state.project.entry===old)state.project.entry=n.id;for(const x of state.project.nodes){if(x.next===old)x.next=n.id;for(const r of x.responses)if(r.target===old)r.target=n.id}state.selected=n.id}else n[key]=e.target.value||null})});
$('#conditions-json').onchange=()=>{try{const value=JSON.parse($('#conditions-json').value);if(!Array.isArray(value))throw Error('Conditions must be an array.');editSelected(n=>n.conditions=value)}catch(e){toast(e.message,true)}};
$('#actions-json').onchange=()=>{try{const value=JSON.parse($('#actions-json').value);if(!Array.isArray(value))throw Error('Actions must be an array.');editSelected(n=>n.actions=value)}catch(e){toast(e.message,true)}};
$('#add-response').onclick=()=>editSelected(n=>n.responses.push({cue:'chat_bubble',label:'Continue',target:'',transition:'IMMEDIATE',actions:[]}));
$('#add-card').onclick=()=>{snapshot();let i=1;while(state.project.nodes.some(n=>n.id===`new_card_${i}`))i++;const n={id:`new_card_${i}`,type:'DIALOGUE',title:'New card',trigger:null,conditions:[],text:'',tooltip:false,speaker:null,responses:[],actions:[],next:null,ending:null,editor:{x:120,y:120}};state.project.nodes.push(n);state.selected=n.id;changed()};
$('#delete-card').onclick=()=>{const n=selected();if(!n||!confirm(`Delete ${n.id}? Incoming links will need repair.`))return;snapshot();state.project.nodes=state.project.nodes.filter(x=>x!==n);state.selected=null;changed()};
$('#undo').onclick=()=>restore(state.undo,state.redo);$('#redo').onclick=()=>restore(state.redo,state.undo);$('#save').onclick=save;
$('#simulate').onclick=()=>$('#simulation-dialog').showModal();$('#run-simulation').onclick=runSimulation;
const exportButton=document.createElement('button');exportButton.textContent='Export';exportButton.onclick=()=>$('#export-dialog').showModal();$('#simulate').after(exportButton);$('#run-export').onclick=runExport;
$('#search').oninput=e=>{state.search=e.target.value;renderOutline();renderCanvas()};$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderOutline();renderCanvas()});
addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();restore(e.shiftKey?state.redo:state.undo,e.shiftKey?state.undo:state.redo)}});addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});
function toast(message,error=false){const t=$('#toast');t.textContent=message;t.style.background=error?'#9d3831':'';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}function json(s){return JSON.parse(s||'{}')}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(s){return esc(s)}
load();
