package moeblocks.mod.init;

import moeblocks.mod.MoeMod;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class MoeSounds {
    public static final DeferredRegister<SoundEvent> REGISTRY = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, MoeMod.ID);

    public static final RegistryObject<SoundEvent> MOE_ATTACK = REGISTRY.register("entity.moe.attack", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.attack")));
    public static final RegistryObject<SoundEvent> MOE_BELL_STEP = REGISTRY.register("entity.moe.bell.step", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.bell.step")));
    public static final RegistryObject<SoundEvent> MOE_DEAD = REGISTRY.register("entity.moe.dead", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.dead")));
    public static final RegistryObject<SoundEvent> MOE_EAT = REGISTRY.register("entity.moe.eat", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.eat")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_ANGRY = REGISTRY.register("entity.moe.emotion.angry", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.angry")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_BEGGING = REGISTRY.register("entity.moe.emotion.begging", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.begging")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_CONFUSED = REGISTRY.register("entity.moe.emotion.confused", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.confused")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_CRYING = REGISTRY.register("entity.moe.emotion.crying", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.crying")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_EMBARRASSED = REGISTRY.register("entity.moe.emotion.embarrassed", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.embarrassed")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_HAPPY = REGISTRY.register("entity.moe.emotion.happy", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.happy")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_MISCHIEVOUS = REGISTRY.register("entity.moe.emotion.mischievous", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.mischievous")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_NORMAL = REGISTRY.register("entity.moe.emotion.normal", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.normal")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_PAINED = REGISTRY.register("entity.moe.emotion.pained", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.pained")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_PSYCHOTIC = REGISTRY.register("entity.moe.emotion.psychotic", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.psychotic")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_SCARED = REGISTRY.register("entity.moe.emotion.scared", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.scared")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_SMITTEN = REGISTRY.register("entity.moe.emotion.smitten", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.smitten")));
    public static final RegistryObject<SoundEvent> MOE_EMOTION_TIRED = REGISTRY.register("entity.moe.emotion.tired", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.emotion.tired")));
    public static final RegistryObject<SoundEvent> MOE_GREET_LEVEL_1 = REGISTRY.register("entity.moe.greet.level_1", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.greet.level_1")));
    public static final RegistryObject<SoundEvent> MOE_GREET_LEVEL_2 = REGISTRY.register("entity.moe.greet.level_2", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.greet.level_2")));
    public static final RegistryObject<SoundEvent> MOE_GREET_LEVEL_3 = REGISTRY.register("entity.moe.greet.level_3", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.greet.level_3")));
    public static final RegistryObject<SoundEvent> MOE_GREET_LEVEL_4 = REGISTRY.register("entity.moe.greet.level_4", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.greet.level_4")));
    public static final RegistryObject<SoundEvent> MOE_HURT = REGISTRY.register("entity.moe.hurt", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.hurt")));
    public static final RegistryObject<SoundEvent> MOE_NO = REGISTRY.register("entity.moe.no", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.no")));
    public static final RegistryObject<SoundEvent> MOE_SING = REGISTRY.register("entity.moe.sing", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.sing")));
    public static final RegistryObject<SoundEvent> MOE_THANK_YOU = REGISTRY.register("entity.moe.thank_you", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.thank_you")));
    public static final RegistryObject<SoundEvent> MOE_YES = REGISTRY.register("entity.moe.yes", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.moe.yes")));
    public static final RegistryObject<SoundEvent> MUSIC_DISC_POMF_POMF = REGISTRY.register("music_disc.pomf_pomf", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "music_disc.pomf_pomf")));
    public static final RegistryObject<SoundEvent> SENPAI_ATTACK = REGISTRY.register("entity.senpai.attack", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.attack")));
    public static final RegistryObject<SoundEvent> SENPAI_DEAD = REGISTRY.register("entity.senpai.dead", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.dead")));
    public static final RegistryObject<SoundEvent> SENPAI_EAT = REGISTRY.register("entity.senpai.eat", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.eat")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_ANGRY = REGISTRY.register("entity.senpai.emotion.angry", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.angry")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_BEGGING = REGISTRY.register("entity.senpai.emotion.begging", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.begging")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_CONFUSED = REGISTRY.register("entity.senpai.emotion.confused", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.confused")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_CRYING = REGISTRY.register("entity.senpai.emotion.crying", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.crying")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_EMBARRASSED = REGISTRY.register("entity.senpai.emotion.embarrassed", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.embarrassed")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_HAPPY = REGISTRY.register("entity.senpai.emotion.happy", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.happy")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_MISCHIEVOUS = REGISTRY.register("entity.senpai.emotion.mischievous", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.mischievous")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_NORMAL = REGISTRY.register("entity.senpai.emotion.normal", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.normal")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_PAINED = REGISTRY.register("entity.senpai.emotion.pained", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.pained")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_PSYCHOTIC = REGISTRY.register("entity.senpai.emotion.psychotic", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.psychotic")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_SCARED = REGISTRY.register("entity.senpai.emotion.scared", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.scared")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_SMITTEN = REGISTRY.register("entity.senpai.emotion.smitten", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.smitten")));
    public static final RegistryObject<SoundEvent> SENPAI_EMOTION_TIRED = REGISTRY.register("entity.senpai.emotion.tired", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.emotion.tired")));
    public static final RegistryObject<SoundEvent> SENPAI_GREET_LEVEL_1 = REGISTRY.register("entity.senpai.greet.level_1", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.greet.level_1")));
    public static final RegistryObject<SoundEvent> SENPAI_GREET_LEVEL_2 = REGISTRY.register("entity.senpai.greet.level_2", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.greet.level_2")));
    public static final RegistryObject<SoundEvent> SENPAI_GREET_LEVEL_3 = REGISTRY.register("entity.senpai.greet.level_3", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.greet.level_3")));
    public static final RegistryObject<SoundEvent> SENPAI_GREET_LEVEL_4 = REGISTRY.register("entity.senpai.greet.level_4", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.greet.level_4")));
    public static final RegistryObject<SoundEvent> SENPAI_HURT = REGISTRY.register("entity.senpai.hurt", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.hurt")));
    public static final RegistryObject<SoundEvent> SENPAI_NO = REGISTRY.register("entity.senpai.no", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.no")));
    public static final RegistryObject<SoundEvent> SENPAI_SING = REGISTRY.register("entity.senpai.sing", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.sing")));
    public static final RegistryObject<SoundEvent> SENPAI_THANK_YOU = REGISTRY.register("entity.senpai.thank_you", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.thank_you")));
    public static final RegistryObject<SoundEvent> SENPAI_YES = REGISTRY.register("entity.senpai.yes", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "entity.senpai.yes")));
    public static final RegistryObject<SoundEvent> YEARBOOK_SIGN = REGISTRY.register("item.yearbook.sign", () -> new SoundEvent(new ResourceLocation(MoeMod.ID, "itme.yearbook.sign")));
}
